export const activitiesData = [
  {
    id: 1,
    name: 'Ajedrez',
    campus: 'Campus Casa Central',
    imageUrl: 'https://www.clarin.com/img/2024/10/10/IUl8ywHqRO_2000x1500__1.jpg',
    professor: 'Raúl Molina Muñoz',
    venue: 'Sala de Estar',
    schedule: 'Jueves: 12:30 - 13:40',
  },
  {
    id: 2,
    name: 'Básquetbol',
    campus: 'Campus Casa Central',
    imageUrl: 'https://usm.cl/noticias/usm-da-el-vamos-oficial-a-campeonato-nacional-de-basquetbol-masculino-fenaude-2023/img_0293/',
    professor: 'Profesor X',
    venue: 'Cancha Principal',
    schedule: 'Lunes y Miércoles: 10:00 - 11:30',
  },
  {
    id: 3,
    name: 'Fútbol',
    campus: 'Campus Casa Central',
    imageUrl: 'https://assets.diarioconcepcion.cl/2023/06/pag-1-futbol-adesup-udec-vs-virginio-gomez-foto-raphael-850x500.jpg',
    professor: 'Profesor Y',
    venue: 'Cancha 1',
    schedule: 'Martes y Jueves: 15:00 - 16:30',
  },
  {
    id: 4,
    name: 'Futsal',
    campus: 'Campus Casa Central',
    imageUrl: 'https://defider.usm.cl/wp-content/uploads/2022/10/FINAL-UVM-USACH-24.jpg',
    professor: 'Profesor Z',
    venue: 'Gimnasio',
    schedule: 'Miércoles y Viernes: 17:00 - 18:30',
  },
  {
    id: 5,
    name: 'Tenis de Mesa',
    campus: 'Campus San Joaquín',
    imageUrl: 'URL_IMAGEN_TENIS_DE_MESA',
    professor: 'Profesor A',
    venue: 'Polideportivo',
    schedule: 'Lunes y Jueves: 09:00 - 10:30',
  },
  {
    id: 6,
    name: 'Básquetbol 3x3',
    campus: 'Campus San Joaquín / Vitacura',
    imageUrl: 'URL_IMAGEN_BASQUETBOL_3X3',
    professor: 'Profesor B',
    venue: 'Canchas Exteriores',
    schedule: 'Martes y Viernes: 11:00 - 12:30',
  },
  {
    id: 7,
    name: 'Karate',
    campus: 'Campus San Joaquín / Vitacura',
    imageUrl: 'URL_IMAGEN_KARATE',
    professor: 'Sensei C',
    venue: 'Dojo',
    schedule: 'Lunes y Miércoles: 19:00 - 20:30',
  },
  {
    id: 8,
    name: 'Futsal',
    campus: 'Campus San Joaquín',
    imageUrl: 'URL_IMAGEN_FUTSAL_SAN_JOAQUIN',
    professor: 'Profesor D',
    venue: 'Gimnasio 2',
    schedule: 'Jueves: 16:00 - 17:30',
  },
  // Agrega más actividades según sea necesario
];